### ISSUE TITLE
Ivy class not found

### ISSUE THREAD

**Issue by ouryperd** [Enroi/GroovyScripts#1]
Test code:

```
def s = "A silly string with words"
@Grab(group='org.apache.commons', module='commons-lang3', version='3.3.2')
def ss = org.apache.commons.lang3.text.WordUtils.capitalizeFully(s)
assert ss == 'A Silly String With Words'
println ss
```

Error:

```
java.lang.ClassNotFoundException: org.apache.ivy.util.MessageLogger
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: org.apache.ivy.util.MessageLogger starting from ModuleCL@5b34d930[org.vorlyanskiy.netbeans.groovy] with possible defining loaders null and declared parents [org.netbeans.JarClassLoader@45949842, ModuleCL@75a8df8e[org.openide.awt], ModuleCL@5fb4dca0[org.openide.nodes], ModuleCL@7c9aad61[org.netbeans.api.progress], ModuleCL@53deccbd[org.openide.dialogs], ModuleCL@7ae81893[org.netbeans.modules.projectuiapi], ModuleCL@57889baa[org.netbeans.modules.projectapi], ModuleCL@48839e09[org.netbeans.modules.options.api], ModuleCL@6a43fb8[org.openide.loaders], ModuleCL@1640eb7b[org.openide.io], ...2 more]
at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: org/apache/ivy/util/MessageLogger
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at groovy.grape.Grape.getInstance(Grape.java:126)
at groovy.grape.Grape$1.run(Grape.java:163)
at groovy.grape.Grape$1.run(Grape.java:160)
at java.security.AccessController.doPrivileged(Native Method)
at groovy.grape.Grape.grab(Grape.java:160)
at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:377)
at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:426)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:479)
at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.run(RunnerScriptInternal.java:38)
at org.openide.util.Task.run(Task.java:232)
at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by ouryperd** [comment]
This is on Run Internal. On Run External it works :-)

**Comment by Enroi** [comment]
It has been fixed yesterday.
