### ISSUE TITLE
Error when building and general instability after plugin install

### ISSUE THREAD

**Issue by ouryperd** [Enroi/GroovyScripts#6]
On Install in Development IDE:

```
java.lang.ClassNotFoundException: org.netbeans.modules.progress.spi.RunOffEDTProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: org.netbeans.modules.progress.spi.RunOffEDTProvider starting from ModuleCL@61265c18[org.netbeans.api.progress.nb] with possible defining loaders [ModuleCL@61265c18[org.netbeans.api.progress.nb]] and declared parents [org.netbeans.JarClassLoader@7ccdd25c, ModuleCL@35e22157[org.netbeans.api.progress], ModuleCL@49ce2edb[org.openide.awt]]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: org/netbeans/modules/progress/spi/RunOffEDTProvider
	at org.netbeans.modules.welcome.content.RecentProjectsPanel$OpenProjectAction.actionPerformed(RecentProjectsPanel.java:224)
	at org.netbeans.modules.welcome.content.ActionButton.actionPerformed(ActionButton.java:54)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Console output

```
--- nbm-maven-plugin:4.5:nbm (default-nbm) @ groovy-scripts ---
Copying module JAR to D:\D\projects\NetBeansProjects\GroovyScripts\target\nbm\netbeans\extra\modules with manifest updates
Using 'UTF-8' encoding to copy filtered resources.
Copying 1 resource
Generating Auto Update information for org.vorlyanskiy.netbeans.groovy
No updater.jar specified, cannot validate Info.xml against DTD
Building jar: D:\D\projects\NetBeansProjects\GroovyScripts\target\nbm\groovy-scripts-1.3-SNAPSHOT.nbm
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  20.450 s
Finished at: 2021-02-15T07:39:08+02:00
------------------------------------------------------------------------
NetBeans: Deploying NBM module in development IDE...
Deploying test module D:\D\projects\NetBeansProjects\GroovyScripts\target\nbm\netbeans\extra\modules\ru-nichost-enroi-groovy-scripts.jar...
Disabling StandardModule:org.vorlyanskiy.netbeans.groovy jarFile: D:\D\projects\NetBeansProjects\GroovyScripts\target\nbm\netbeans\extra\modules\ru-nichost-enroi-groovy-scripts.jar...
Enabling StandardModule:org.vorlyanskiy.netbeans.groovy jarFile: D:\D\projects\NetBeansProjects\GroovyScripts\target\nbm\netbeans\extra\modules\ru-nichost-enroi-groovy-scripts.jar...
Done.
```

**Comment by ouryperd** [comment]
New error:

```
java.lang.IllegalArgumentException: file:/D:/D/projects/NetBeansProjects/siteSnippets/lib/nblibraries.properties
	at org.netbeans.api.project.libraries.LibraryManager.forLocation(LibraryManager.java:513)
	at org.netbeans.modules.project.ant.ProjectLibraryProvider.getProjectLibraryManager(ProjectLibraryProvider.java:1147)
	at org.netbeans.spi.project.support.ant.ReferenceHelper.getProjectLibraryManager(ReferenceHelper.java:1485)
	at org.netbeans.spi.project.support.ant.ReferenceHelper.findLibrary(ReferenceHelper.java:1573)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders.getReferenceProblems(ProjectProblemsProviders.java:363)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders.access$1200(ProjectProblemsProviders.java:107)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders$ReferenceProblemProviderImpl$1.lambda$collectProblems$0(ProjectProblemsProviders.java:1212)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.openide.util.Mutex.readAccess(Mutex.java:193)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders$ReferenceProblemProviderImpl$1.collectProblems(ProjectProblemsProviders.java:1209)
	at org.netbeans.spi.project.ui.support.ProjectProblemsProviderSupport.getProblems(ProjectProblemsProviderSupport.java:97)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders$ReferenceProblemProviderImpl.getProblems(ProjectProblemsProviders.java:1206)
	at org.netbeans.spi.project.ui.support.UILookupMergerSupport$ProjectProblemsProviderImpl.getProblems(UILookupMergerSupport.java:274)
	at org.netbeans.modules.project.ui.problems.BrokenProjectAnnotator$2.run(BrokenProjectAnnotator.java:121)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by Enroi** [comment]
What version of NetBeans do you use for compile this plugin?

**Comment by Enroi** [comment]
I use NetBeans 12.2

**Comment by ouryperd** [comment]
12.2

**Comment by Enroi** [comment]
I can not reproduce it.
What I have tried:

1. I have download NetBeans 12.2 zip from http://netbeans.apache.org/download/nb122/nb122.html
2. I have extracted and start this clear NetBeans with separate cachedir and userdir with such command netbeans64.exe --userdir c:\temp\ud2 --cachedir c:\temp\cd2
3. I have download my plugin from git@github.com:Enroi/GroovyScripts.git
4. I have executed action "Install/Reload in development IDE".
5. I used java 11.
It works. Result log file I have attached here.
Result comments and questions.
1. What version of Java do you use for start NetBeans? It can be found in NetBeans menu item Help->About. If you use Java8 it is problem. Source module for class RunOffEDTProvider is org-netbeans-api-progress.jar. It requires OpenIDE-Module-Java-Dependencies: Java > 1.8.
2. Can you repeat my steps ? Will you have the same problem ? You can use your current NetBeans with command like this netbeans64.exe --userdir c:\temp\ud2 --cachedir c:\temp\cd2
3. Do you have file platform\modules\org-netbeans-api-progress.jar  in your NetBeans?

[result.log](https://github.com/Enroi/GroovyScripts/files/6018741/result.log)

**Comment by ouryperd** [comment]
My Netbeans runs on openjdk 8 and the project is an openjdk s11 project. I will repeat your steps and feedback. I do have org-netbeans-api-progress.jar.

**Comment by ouryperd** [comment]
I was successful in building the plugin with the instructions above. When opening a Groovy script in an editor, I got the following error:

```
java.lang.NoClassDefFoundError: org/netbeans/api/java/source/JavaSource
	at org.netbeans.api.java.source.support.OpenedEditors.stateChanged(OpenedEditors.java:141)
	at org.netbeans.api.java.source.support.OpenedEditors$1.propertyChange(OpenedEditors.java:66)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at org.netbeans.api.editor.EditorRegistry.fireEvents(EditorRegistry.java:544)
	at org.netbeans.api.editor.EditorRegistry.focusLost(EditorRegistry.java:373)
	at org.netbeans.api.editor.EditorRegistry$FocusL.focusLost(EditorRegistry.java:681)
	at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:230)
	at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229)
	at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229)
	at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229)
	at java.awt.Component.processFocusEvent(Component.java:6431)
	at java.awt.Component.processEvent(Component.java:6295)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1024)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:690)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ouryperd** [comment]
Able to open script, when running with bundled Groovy. Where it says `Caused: BUG! exception in phase 'conversion' in source unit 'D:\D\Project\Portable-apps\other\soapui,` that source is not near my netbeans projects. I don't know how NB parses that file at all, it's not supposed to.

```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.openide.util.Task
java.lang.NullPointerException
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitIfElse(CodeVisitorSupport.java:111)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitIfElse(ClassCodeVisitorSupport.java:212)
	at org.codehaus.groovy.ast.stmt.IfStatement.visit(IfStatement.java:41)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:164)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitIfElse(CodeVisitorSupport.java:111)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitIfElse(ClassCodeVisitorSupport.java:212)
	at org.codehaus.groovy.ast.stmt.IfStatement.visit(IfStatement.java:41)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:164)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:106)
	at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1099)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1092)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:216)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
Caused: BUG! exception in phase 'conversion' in source unit 'D:\D\Project\Portable-apps\other\soapui\source\soapui-2.0\src\java\com\eviware\soapui\impl\wsdl\actions\project\CloseProjectAction.java' null
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:905)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:244)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:61)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.lambda$compileJavaFiles$1(RunnerScriptInternal.java:56)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.compileJavaFiles(RunnerScriptInternal.java:54)
	at org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.run(RunnerScriptInternal.java:40)
	at org.openide.util.Task.run(Task.java:232)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.control.CompilationUnit arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class groovy.lang.GroovyClassLoader arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.ast.CodeVisitorSupport arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.ast.ClassCodeVisitorSupport arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.ast.stmt.IfStatement arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.ast.stmt.BlockStatement arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.ast.ClassNode arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class groovy.grape.GrabAnnotationTransformation arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.codehaus.groovy.transform.ASTTransformationVisitor arbitrarily from one of ModuleCL@3ab8b450[org.vorlyanskiy.netbeans.groovy] and ModuleCL@47ca9a45[org.netbeans.modules.libs.groovy] starting from SystemClassLoader[755 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
```

**Comment by ouryperd** [comment]
Can't reproduce anymore. Using Java 11 works to build and install plugin. I will log new issue for running error.
