### ISSUE TITLE
[Feature Request] - add ability to add jar libs to a Groovy project

### ISSUE THREAD

**Issue by ouryperd** [Enroi/GroovyScripts#7]

**Comment by ouryperd** [comment]
This works, but when running, I get:

`java.lang.NullPointerException
	at org.codehaus.groovy.control.io.AbstractReaderSource.getLine(AbstractReaderSource.java:76)
	at org.codehaus.groovy.control.SourceUnit.getSample(SourceUnit.java:279)
	at org.codehaus.groovy.control.messages.SyntaxErrorMessage.write(SyntaxErrorMessage.java:54)
	at org.codehaus.groovy.control.ErrorCollector.write(ErrorCollector.java:306)
	at org.codehaus.groovy.control.ErrorCollector.write(ErrorCollector.java:326)
	at org.codehaus.groovy.control.MultipleCompilationErrorsException.getMessage(MultipleCompilationErrorsException.java:59)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at org.netbeans.core.NbErrorManager$Exc.getLocalizedMessage(NbErrorManager.java:213)
	at org.netbeans.core.NotifyExcPanel$2.run(NotifyExcPanel.java:279)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

and in the output console:

`org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295)
org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:914)
org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
groovy.lang.GroovyShell.parse(GroovyShell.java:538)
groovy.lang.GroovyShell.evaluate(GroovyShell.java:426)
groovy.lang.GroovyShell.evaluate(GroovyShell.java:479)
org.vorlyanskiy.netbeans.groovy.actions.RunnerScriptInternal.run(RunnerScriptInternal.java:43)
org.openide.util.Task.run(Task.java:232)
org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
`

**Comment by ouryperd** [comment]
Also:

- when adding multiple jars, allow the file dialog to remember location of first added jar, else I have to navigate from home everytime
- make jars visible in project pane

**Comment by ouryperd** [comment]
Please consider making the jar icon the same as the Java jar icon.

**Comment by Enroi** [comment]
Icon for library has been replaced.

**Comment by Enroi** [comment]
Propose to close.
