### ISSUE TITLE
Issue when building after icons were added

### ISSUE THREAD

**Issue by ouryperd** [Enroi/GroovyScripts#9]
When builing:

```
java.lang.NullPointerException
	at org.vorlyanskiy.netbeans.groovy.nodes.LibraryChildren.initCollection(LibraryChildren.java:28)
	at org.openide.nodes.Children$Array.getCollection(Children.java:781)
	at org.openide.nodes.Children$SortedArray$SAE.nodes(Children.java:1184)
[catch] at org.openide.nodes.ChildrenArray.nodesFor(ChildrenArray.java:124)
	at org.openide.nodes.EntrySupportDefault$Info.nodes(EntrySupportDefault.java:782)
	at org.openide.nodes.EntrySupportDefault.justComputeNodes(EntrySupportDefault.java:172)
	at org.openide.nodes.ChildrenArray.nodes(ChildrenArray.java:63)
	at org.openide.nodes.EntrySupportDefault.getNodes(EntrySupportDefault.java:107)
	at org.openide.nodes.EntrySupportDefault.getNodes(EntrySupportDefault.java:149)
	at org.openide.nodes.Children.getNodes(Children.java:444)
	at org.openide.nodes.Children.findChild(Children.java:389)
	at org.openide.nodes.EntrySupportDefault.getNodes(EntrySupportDefault.java:143)
	at org.openide.nodes.EntrySupportDefault.getNodesCount(EntrySupportDefault.java:153)
	at org.openide.nodes.Children.getNodesCount(Children.java:495)
	at org.openide.nodes.FilterNode$Children$DefaultSupport.callGetNodesCount(FilterNode.java:1658)
	at org.openide.nodes.FilterNode$Children.getNodesCount(FilterNode.java:1609)
	at org.openide.explorer.view.TreeView$6.run(TreeView.java:971)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by ouryperd** [comment]
NB hangs and has to be killed.

**Comment by Enroi** [comment]
Fixed.

**Comment by ouryperd** [comment]
New after latest:
`java.lang.IllegalArgumentException: file:/D:/D/projects/NetBeansProjects/siteSnippets/lib/nblibraries.properties
	at org.netbeans.api.project.libraries.LibraryManager.forLocation(LibraryManager.java:513)
	at org.netbeans.modules.project.ant.ProjectLibraryProvider.getProjectLibraryManager(ProjectLibraryProvider.java:1147)
	at org.netbeans.spi.project.support.ant.ReferenceHelper.getProjectLibraryManager(ReferenceHelper.java:1485)
	at org.netbeans.spi.project.support.ant.ReferenceHelper.findLibrary(ReferenceHelper.java:1573)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders.getReferenceProblems(ProjectProblemsProviders.java:363)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders.access$1200(ProjectProblemsProviders.java:107)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders$ReferenceProblemProviderImpl$1.lambda$collectProblems$0(ProjectProblemsProviders.java:1212)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders$ReferenceProblemProviderImpl$1.collectProblems(ProjectProblemsProviders.java:1209)
	at org.netbeans.spi.project.ui.support.ProjectProblemsProviderSupport.getProblems(ProjectProblemsProviderSupport.java:97)
	at org.netbeans.modules.java.project.ui.ProjectProblemsProviders$ReferenceProblemProviderImpl.getProblems(ProjectProblemsProviders.java:1206)
	at org.netbeans.spi.project.ui.support.UILookupMergerSupport$ProjectProblemsProviderImpl.getProblems(UILookupMergerSupport.java:274)
	at org.netbeans.modules.project.ui.problems.BrokenProjectAnnotator$2.run(BrokenProjectAnnotator.java:121)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)`

**Comment by Enroi** [comment]
How to reproduce it? 
Caption of issue has text "Issue when building". I did build and "clean and build" many times, I can not reproduce this problem.

**Comment by ouryperd** [comment]
tested. Doesn't happen any more.
